### ISSUE TITLE
Bot reports are tremendously verbose

### ISSUE THREAD

**Issue by cromulus** [18F/standup-bot#132]
Our slack channel reports both individual responses as well  as updating the summary... For larger teams, this means that the summary is several pages above where the last person responded.

For the individual report, all I want to know is that the person responded, and the original, first summary updates appropriately.

It seems we could achieve the goals of the standup bot with it being a whole heck of a lot less verbose.

**Comment by cromulus** [comment]
Essentially, this line: https://github.com/18F/standup-slack-bot/blob/develop/lib/helpers/updateChannelReport.js#L25

Results in the "report" being posted several times over in the channel, which gets super noisy.

**Comment by mgwalker** [comment]
Thanks for the report, and apologies for not responding sooner!  We agree, FWIW, but we haven't had time to fix it.

One thing we've considered is an option to disable the updates altogether. Another thing we've thought about is since Slack added threads, the bot could add standup reports to a thread. Then they'd be consolidated in one place and take up even less real estate.

**Comment by mgwalker** [comment]
Closing with #140.  Feel free to comment, reopen, or create a new issue if this isn't helpful.
