### ISSUE TITLE
Allow users to set themselves OOO for a period of time

### ISSUE THREAD

**Issue by mgwalker** [18F/standup-bot#70]
If someone knows they're going to be OOO, it might be nice to let standup bot know.  It can even prefill their reports.  Will put in a proper user story later, but some ideas (in a DM, presumably):

```
ooo for 3 days
ooo until wednesday
ooo through tuesday
```

And their report could just be a **Today** set to "Out of office" - possibly the OOO folks get rolled up in the summary?

**Comment by stvnrlly** [comment]
I like the idea of putting `OOO` in the summary. I'm not sure about prefilling, since we don't have a way for the bot to know who it expects to hear from. It also seems that people who are "out" sometimes do the standup anyway.

At a higher level, this is something that the bot could potentially pull from people's display names (since there's a norm of putting OOO in it when out). I wish there were an API method for editing the display name, so that we could make it more interactive.

**Comment by mgwalker** [comment]
They could put the channel name when they tell the bot:  `#channel ooo for 3 days`, or use the channel name if someone says it from within the channel.  But yeah, you've got a point.

**Comment by stvnrlly** [comment]
Ah, yes: this could be a good way to try out pre-population commands. Although, for this one, I wonder if we'd be building a feature that should really exist in Tock.

**Comment by stvnrlly** [comment]
Another challenge here: should the bot differentiate between all-day OOO and part-day OOO? And, if so, how?

**Comment by mgwalker** [comment]
What if the bot just looks for "OOO" in the "today" part of the user's standup?  That doesn't help with the pre-populated thing, but it'd solve the all-day/part-day thing, and if someone is OOO but still wants to submit their standup, it'll handle that too.

**Comment by stvnrlly** [comment]
That's what I have written now (not pushed yet), but I don't think it would handle all-day/part-day. There's just too much variation in how people say it. I'm fine to let it be broad for now, though, and see if that's ok.

**Comment by mgwalker** [comment]
@waldoj kind of brought this question back up, particularly around all-day/part-day OOO.  Is it something we should look into again?

Also, to the question of knowing which users should respond, this is similar to #101 - if the channel's standup is setup with an audience more specific then `@here` or `@channel`, the bot could infer that anyone in that audience who has marked themselves OOO should get an auto-filled OOO report.  But I suspect that's a pretty narrow use case - out of the 9 channels using the bot in the TTS Slack, only 3 have audiences set.

For automatic OOO reports, the bot could also submit them to every channel where the user is present and there's a standup scheduled.

**Comment by stvnrlly** [comment]
I'm not sure that standup reports are considered mandatory enough that non-responders could be auto-marked as OOO. Here's a counter-proposal:

- If the full content of `today` is "OOO", mark the submitter as out-of-office.
- If the content includes "OOO" but also other stuff, either mark the submitter as partly out-of-office or do nothing. I'm kind of leaning towards the latter, since the person will still be around.
- Create a new command—possibly `#[channel-name] ooo [number]`—which creates standup responses for the next `[number]` business days that just has a "OOO" response. That way, they'll still get included in the report, and will be listed as out-of-office.

**Comment by waldoj** [comment]
👍  This is very sensible.

(I appreciate that you're probably using "OOO" as a shorthand here, but just in case: make sure that `out of office` is also a triggering phrase, too. I'm trying to eliminate my use of insular shorthand.)

**Comment by mgwalker** [comment]
Yep, your third bullet aligns with what I was thinking.  And I really like the other two bullets as well.  It sounds like we have a path forward.
